import math

game=True
WIDTH=1200
HEIGHT= 800
HALF_WIDTH=WIDTH // 2
HALF_HEIGHT=HEIGHT // 2
PENTA_HEIGHT = 5 * HEIGHT
DOUBLE_HEIGHT = 2 * HEIGHT
FPS=1000
TILE=100
mouse_sensor = 0.002

#mini map
MINI_MAP_SCALE = 5
MAP_SCALE = 3 * MINI_MAP_SCALE
MINI_MAP_RES = (WIDTH // MINI_MAP_SCALE, HEIGHT // MINI_MAP_SCALE)
MAP_TILE = TILE // MAP_SCALE
MAP_POSITION=(10,10)


#player
POSITION=(190, 2450)
SPEED = 4
ANGLE = 0
TURNING_FORCE=0.05
info = True

#ray casting
mode = 'normal'
FOV = math.pi / 3
HALF_FOV = FOV / 2
NUM_RAYS = 300
MAX_DEPTH = 800
DELTA_ANGLE = FOV / NUM_RAYS
DIST = NUM_RAYS / (2 * math.tan(HALF_FOV))
PROJ_COEFF = 3 * DIST * TILE
SCALE = WIDTH // NUM_RAYS

#objects / sprites
DOUBLE_PI = 2 * math.pi
CENTER_RAY = NUM_RAYS // 2 - 1
FAKE_RAYS = 100
FAKE_RAYS_RANGE = NUM_RAYS + 1 + 2 * FAKE_RAYS

#colors
BLUE = ()
RED = ()
GREEN = ()
BLAK = ()
WHITE = ()
GREY = ()

#textures
TEXTURE_WIDTH =1200
TEXTURE_HEIGHT = 800
TEXTURE_SCALE = TEXTURE_WIDTH // TILE


#
